# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import myimages

class Ui_VI_Accessment_System(object):
    def setupUi(self, VI_Accessment_System):
        VI_Accessment_System.setObjectName("VI_Accessment_System")
        VI_Accessment_System.resize(1002, 717)
        VI_Accessment_System.setMouseTracking(False)
        icon = QtGui.QIcon.fromTheme("8")
        VI_Accessment_System.setWindowIcon(icon)
        VI_Accessment_System.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(VI_Accessment_System)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout_2.addWidget(self.comboBox_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_2.addWidget(self.comboBox_5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setMinimumSize(QtCore.QSize(400, 80))
        self.textBrowser.setMaximumSize(QtCore.QSize(3000, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 2, 5, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_4.addWidget(self.graphicsView_2, 1, 3, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.page_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 1, 2, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 2, 4, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_4.addWidget(self.treeWidget, 0, 0, 3, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.line_2 = QtWidgets.QFrame(self.page_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 1, 1, 2, 1)
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_2.sizePolicy().hasHeightForWidth())
        self.treeWidget_2.setSizePolicy(sizePolicy)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setText(0, "1")
        self.gridLayout_7.addWidget(self.treeWidget_2, 1, 0, 4, 1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.page_5)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout_9.addWidget(self.graphicsView_3, 1, 1, 3, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_9.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_9.addWidget(self.tabWidget, 5, 1, 1, 2)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.page_5)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_9.addWidget(self.graphicsView_5, 1, 2, 2, 1)
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.page_5)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_9.addWidget(self.graphicsView_4, 3, 2, 1, 1)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget_2.addWidget(self.page_6)
        self.gridLayout_7.addWidget(self.stackedWidget_2, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_3.sizePolicy().hasHeightForWidth())
        self.treeWidget_3.setSizePolicy(sizePolicy)
        self.treeWidget_3.setObjectName("treeWidget_3")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_6.addWidget(self.treeWidget_3, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.groupBox_3)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_9 = QtWidgets.QLabel(self.page_9)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_9)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_9)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 1, 4, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_9)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_11.addWidget(self.checkBox_2, 5, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.page_9)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_11.addWidget(self.checkBox, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem4, 6, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.page_9)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_11.addWidget(self.comboBox_6, 1, 2, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.page_9)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_11.addWidget(self.comboBox_7, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem5, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_9)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem7, 7, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_9)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_12.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_12.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_12.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_12.addWidget(self.radioButton_4, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_4, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_9)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 5, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.stackedWidget_3.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_13.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_10)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_13.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.page_10)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_13.addWidget(self.checkBox_4, 2, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.stackedWidget_3.addWidget(self.page_10)
        self.gridLayout_8.addWidget(self.stackedWidget_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        VI_Accessment_System.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VI_Accessment_System)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        VI_Accessment_System.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(VI_Accessment_System)
        self.toolBar.setObjectName("toolBar")
        VI_Accessment_System.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiontest = QtWidgets.QAction(VI_Accessment_System)
        self.actiontest.setObjectName("actiontest")
        self.actiontest2 = QtWidgets.QAction(VI_Accessment_System)
        self.actiontest2.setObjectName("actiontest2")
        self.menu_Engine_Working_Dist = QtWidgets.QAction(VI_Accessment_System)
        self.menu_Engine_Working_Dist.setObjectName("menu_Engine_Working_Dist")
        self.menu_InputData = QtWidgets.QAction(VI_Accessment_System)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.menu_InputData.setFont(font)
        self.menu_InputData.setObjectName("menu_InputData")
        self.menu_CalData = QtWidgets.QAction(VI_Accessment_System)
        self.menu_CalData.setObjectName("menu_CalData")
        self.menu_Exit = QtWidgets.QAction(VI_Accessment_System)
        self.menu_Exit.setObjectName("menu_Exit")
        self.menu_Guildlines = QtWidgets.QAction(VI_Accessment_System)
        self.menu_Guildlines.setObjectName("menu_Guildlines")
        self.menu_ContactUs = QtWidgets.QAction(VI_Accessment_System)
        self.menu_ContactUs.setObjectName("menu_ContactUs")
        self.menu_Shifting_Strategy = QtWidgets.QAction(VI_Accessment_System)
        self.menu_Shifting_Strategy.setObjectName("menu_Shifting_Strategy")
        self.menu_Speed_Dist = QtWidgets.QAction(VI_Accessment_System)
        self.menu_Speed_Dist.setObjectName("menu_Speed_Dist")
        self.actionOveralwidget = QtWidgets.QAction(VI_Accessment_System)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/badge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOveralwidget.setIcon(icon)
        self.actionOveralwidget.setObjectName("actionOveralwidget")
        self.actionRatingDetails = QtWidgets.QAction(VI_Accessment_System)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/detail2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRatingDetails.setIcon(icon1)
        self.actionRatingDetails.setObjectName("actionRatingDetails")
        self.actionDataEdit = QtWidgets.QAction(VI_Accessment_System)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/wave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDataEdit.setIcon(icon2)
        self.actionDataEdit.setObjectName("actionDataEdit")
        self.actionSettings = QtWidgets.QAction(VI_Accessment_System)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/setup-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon3)
        self.actionSettings.setObjectName("actionSettings")
        self.actionComparison = QtWidgets.QAction(VI_Accessment_System)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/compare01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionComparison.setIcon(icon4)
        self.actionComparison.setObjectName("actionComparison")
        self.actionDelete = QtWidgets.QAction(VI_Accessment_System)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/images/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon5)
        self.actionDelete.setObjectName("actionDelete")
        self.menu.addAction(self.menu_InputData)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_Exit)
        self.menu_3.addAction(self.menu_Engine_Working_Dist)
        self.menu_3.addAction(self.menu_Shifting_Strategy)
        self.menu_3.addAction(self.menu_Speed_Dist)
        self.menu_2.addAction(self.menu_CalData)
        self.menu_4.addAction(self.menu_Guildlines)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.menu_ContactUs)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionOveralwidget)
        self.toolBar.addAction(self.actionDataEdit)
        self.toolBar.addAction(self.actionRatingDetails)
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionComparison)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()

        self.retranslateUi(VI_Accessment_System)
        self.stackedWidget.setCurrentIndex(3)
        self.stackedWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(VI_Accessment_System)

    def retranslateUi(self, VI_Accessment_System):
        _translate = QtCore.QCoreApplication.translate
        VI_Accessment_System.setWindowTitle(_translate("VI_Accessment_System", "VI Vehicle Accessment System V1.0"))
        self.groupBox.setTitle(_translate("VI_Accessment_System", "GroupBox"))
        self.pushButton_3.setText(_translate("VI_Accessment_System", "Add CombBox"))
        self.label.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.label_2.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.label_3.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.label_4.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.label_5.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.groupBox_2.setTitle(_translate("VI_Accessment_System", "GroupBox"))
        self.pushButton.setText(_translate("VI_Accessment_System", "PushButton"))
        self.pushButton_2.setText(_translate("VI_Accessment_System", "PushButton"))
        self.treeWidget.headerItem().setText(0, _translate("VI_Accessment_System", "评价工况"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("VI_Accessment_System", "DQ"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("VI_Accessment_System", "KeyOn/Off"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("VI_Accessment_System", "Idle"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("VI_Accessment_System", "PRND"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("VI_Accessment_System", "Launch"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("VI_Accessment_System", "TipIn"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("VI_Accessment_System", "DownShifting"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("VI_Accessment_System", "RisingPedal"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("VI_Accessment_System", "ConstantAccStart"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("VI_Accessment_System", "ConstantSpeed"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("VI_Accessment_System", "Energy"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("VI_Accessment_System", "ConstantSpeedFC"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("VI_Accessment_System", "HVAC"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("VI_Accessment_System", "Ride"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("VI_Accessment_System", "SystemGain"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("VI_Accessment_System", "ConstantSpeed"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("VI_Accessment_System", "RoughRoad"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("VI_Accessment_System", "SinRoad"))
        self.treeWidget.topLevelItem(3).child(4).setText(0, _translate("VI_Accessment_System", "TarStripRoad"))
        self.treeWidget.topLevelItem(3).child(5).setText(0, _translate("VI_Accessment_System", "RDShortWaveRoad"))
        self.treeWidget.topLevelItem(3).child(6).setText(0, _translate("VI_Accessment_System", "LongDongRoad"))
        self.treeWidget.topLevelItem(3).child(7).setText(0, _translate("VI_Accessment_System", "StepRoad"))
        self.treeWidget.topLevelItem(3).child(8).setText(0, _translate("VI_Accessment_System", "DecelerationStrip"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("VI_Accessment_System", "NVH"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("VI_Accessment_System", "KeyOn/Off"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("VI_Accessment_System", "Idle"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("VI_Accessment_System", "Launch"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("VI_Accessment_System", "TipIn"))
        self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("VI_Accessment_System", "DownShifting"))
        self.treeWidget.topLevelItem(4).child(5).setText(0, _translate("VI_Accessment_System", "ConstantGearAcc"))
        self.treeWidget.topLevelItem(4).child(6).setText(0, _translate("VI_Accessment_System", "ConstantSpeed"))
        self.treeWidget.topLevelItem(4).child(7).setText(0, _translate("VI_Accessment_System", "GroovedCementRoad"))
        self.treeWidget.topLevelItem(4).child(8).setText(0, _translate("VI_Accessment_System", "RoughRoad"))
        self.treeWidget.topLevelItem(4).child(9).setText(0, _translate("VI_Accessment_System", "DecelerationStrip"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("VI_Accessment_System", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("VI_Accessment_System", "Tab 2"))
        self.treeWidget_3.headerItem().setText(0, _translate("VI_Accessment_System", "评价工况"))
        __sortingEnabled = self.treeWidget_3.isSortingEnabled()
        self.treeWidget_3.setSortingEnabled(False)
        self.treeWidget_3.topLevelItem(0).setText(0, _translate("VI_Accessment_System", "DQ"))
        self.treeWidget_3.topLevelItem(0).child(0).setText(0, _translate("VI_Accessment_System", "KeyOn/Off"))
        self.treeWidget_3.topLevelItem(0).child(1).setText(0, _translate("VI_Accessment_System", "Idle"))
        self.treeWidget_3.topLevelItem(0).child(2).setText(0, _translate("VI_Accessment_System", "PRND"))
        self.treeWidget_3.topLevelItem(0).child(3).setText(0, _translate("VI_Accessment_System", "Launch"))
        self.treeWidget_3.topLevelItem(0).child(4).setText(0, _translate("VI_Accessment_System", "TipIn"))
        self.treeWidget_3.topLevelItem(0).child(5).setText(0, _translate("VI_Accessment_System", "DownShifting"))
        self.treeWidget_3.topLevelItem(0).child(6).setText(0, _translate("VI_Accessment_System", "RisingPedal"))
        self.treeWidget_3.topLevelItem(0).child(7).setText(0, _translate("VI_Accessment_System", "ConstantAccStart"))
        self.treeWidget_3.topLevelItem(0).child(8).setText(0, _translate("VI_Accessment_System", "ConstantSpeed"))
        self.treeWidget_3.topLevelItem(1).setText(0, _translate("VI_Accessment_System", "Energy"))
        self.treeWidget_3.topLevelItem(1).child(0).setText(0, _translate("VI_Accessment_System", "ConstantSpeedFC"))
        self.treeWidget_3.topLevelItem(2).setText(0, _translate("VI_Accessment_System", "HVAC"))
        self.treeWidget_3.topLevelItem(3).setText(0, _translate("VI_Accessment_System", "Ride"))
        self.treeWidget_3.topLevelItem(3).child(0).setText(0, _translate("VI_Accessment_System", "SystemGain"))
        self.treeWidget_3.topLevelItem(3).child(1).setText(0, _translate("VI_Accessment_System", "ConstantSpeed"))
        self.treeWidget_3.topLevelItem(3).child(2).setText(0, _translate("VI_Accessment_System", "RoughRoad"))
        self.treeWidget_3.topLevelItem(3).child(3).setText(0, _translate("VI_Accessment_System", "SinRoad"))
        self.treeWidget_3.topLevelItem(3).child(4).setText(0, _translate("VI_Accessment_System", "TarStripRoad"))
        self.treeWidget_3.topLevelItem(3).child(5).setText(0, _translate("VI_Accessment_System", "RDShortWaveRoad"))
        self.treeWidget_3.topLevelItem(3).child(6).setText(0, _translate("VI_Accessment_System", "LongDongRoad"))
        self.treeWidget_3.topLevelItem(3).child(7).setText(0, _translate("VI_Accessment_System", "StepRoad"))
        self.treeWidget_3.topLevelItem(3).child(8).setText(0, _translate("VI_Accessment_System", "DecelerationStrip"))
        self.treeWidget_3.topLevelItem(4).setText(0, _translate("VI_Accessment_System", "NVH"))
        self.treeWidget_3.topLevelItem(4).child(0).setText(0, _translate("VI_Accessment_System", "KeyOn/Off"))
        self.treeWidget_3.topLevelItem(4).child(1).setText(0, _translate("VI_Accessment_System", "Idle"))
        self.treeWidget_3.topLevelItem(4).child(2).setText(0, _translate("VI_Accessment_System", "Launch"))
        self.treeWidget_3.topLevelItem(4).child(3).setText(0, _translate("VI_Accessment_System", "TipIn"))
        self.treeWidget_3.topLevelItem(4).child(4).setText(0, _translate("VI_Accessment_System", "DownShifting"))
        self.treeWidget_3.topLevelItem(4).child(5).setText(0, _translate("VI_Accessment_System", "ConstantGearAcc"))
        self.treeWidget_3.topLevelItem(4).child(6).setText(0, _translate("VI_Accessment_System", "ConstantSpeed"))
        self.treeWidget_3.topLevelItem(4).child(7).setText(0, _translate("VI_Accessment_System", "GroovedCementRoad"))
        self.treeWidget_3.topLevelItem(4).child(8).setText(0, _translate("VI_Accessment_System", "RoughRoad"))
        self.treeWidget_3.topLevelItem(4).child(9).setText(0, _translate("VI_Accessment_System", "DecelerationStrip"))
        self.treeWidget_3.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("VI_Accessment_System", "GroupBox"))
        self.label_9.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.label_7.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.label_8.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.checkBox_2.setText(_translate("VI_Accessment_System", "CheckBox"))
        self.checkBox.setText(_translate("VI_Accessment_System", "CheckBox"))
        self.label_6.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.groupBox_4.setTitle(_translate("VI_Accessment_System", "GroupBox"))
        self.radioButton_3.setText(_translate("VI_Accessment_System", "RadioButton"))
        self.radioButton_2.setText(_translate("VI_Accessment_System", "RadioButton"))
        self.radioButton.setText(_translate("VI_Accessment_System", "RadioButton"))
        self.radioButton_4.setText(_translate("VI_Accessment_System", "RadioButton"))
        self.label_10.setText(_translate("VI_Accessment_System", "TextLabel"))
        self.pushButton_4.setText(_translate("VI_Accessment_System", "PushButton"))
        self.checkBox_3.setText(_translate("VI_Accessment_System", "CheckBox"))
        self.checkBox_4.setText(_translate("VI_Accessment_System", "CheckBox"))
        self.menu.setTitle(_translate("VI_Accessment_System", "文件 (File)"))
        self.menu_3.setTitle(_translate("VI_Accessment_System", "绘图 (Ploting)"))
        self.menu_2.setTitle(_translate("VI_Accessment_System", "计算 (Calculation)"))
        self.menu_4.setTitle(_translate("VI_Accessment_System", "帮助 (Help)"))
        self.toolBar.setWindowTitle(_translate("VI_Accessment_System", "toolBar"))
        self.actiontest.setText(_translate("VI_Accessment_System", "test"))
        self.actiontest2.setText(_translate("VI_Accessment_System", "test2"))
        self.menu_Engine_Working_Dist.setText(_translate("VI_Accessment_System", "发动机工况点分布 Engine Work Point Dist."))
        self.menu_InputData.setText(_translate("VI_Accessment_System", "导入测试数据 Input Test Data"))
        self.menu_CalData.setText(_translate("VI_Accessment_System", "求解 Solution"))
        self.menu_Exit.setText(_translate("VI_Accessment_System", "退出"))
        self.menu_Guildlines.setText(_translate("VI_Accessment_System", "操作指南 Guildlines"))
        self.menu_ContactUs.setText(_translate("VI_Accessment_System", "联系作者 Contact Us!"))
        self.menu_Shifting_Strategy.setText(_translate("VI_Accessment_System", "换挡策略分布 Shifting Strategy Dist."))
        self.menu_Speed_Dist.setText(_translate("VI_Accessment_System", "速度分布 Speed Dist."))
        self.actionOveralwidget.setText(_translate("VI_Accessment_System", "Overallwidget"))
        self.actionOveralwidget.setToolTip(_translate("VI_Accessment_System", "Overallwidget"))
        self.actionOveralwidget.setShortcut(_translate("VI_Accessment_System", "F1"))
        self.actionRatingDetails.setText(_translate("VI_Accessment_System", "RatingDetails"))
        self.actionRatingDetails.setToolTip(_translate("VI_Accessment_System", "RatingDetails"))
        self.actionRatingDetails.setShortcut(_translate("VI_Accessment_System", "F2"))
        self.actionDataEdit.setText(_translate("VI_Accessment_System", "DataEdit"))
        self.actionSettings.setText(_translate("VI_Accessment_System", "Settings"))
        self.actionComparison.setText(_translate("VI_Accessment_System", "Comparison"))
        self.actionDelete.setText(_translate("VI_Accessment_System", "Delete"))
